version: "3.8"

services:
  db:
    image: ${DB_IMAGE}
    container_name: database
    restart: always
    ports:
      - 3306:3306
    networks:
      app_net:
        ipv4_address: 172.100.1.3

  nginx:
    build: nginx
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - 80:80
    volumes:
      - ./www:/var/www/html
    links:
      - wordpress
    networks:
      app_net:
        ipv4_address: 172.100.1.4

  wordpress:
    build: wordpress
    container_name: wordpress
    restart: always
    depends_on:
      - db
    ports:
      - 9000:9000
    volumes:
      - ./www:/var/www/html
    networks:
      app_net:
        ipv4_address: 172.100.1.2

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.100.1.0/24
