version: "3.8"

services:
  db:
    build: mysql
    container_name: database
    restart: always
    ports:
      - 3306:3306
    networks:
      - app-network

  wordpress:
    build: wordpress
    container_name: wordpress
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 80:80
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
