version: "3.8"

services:
  db:
    image: ${DB_IMAGE}
    container_name: database
    restart: always
    ports:
      - 3306:3306
    networks:
      app_net:
        ipv4_address: 172.100.1.3

  nginx:
    image: ${NGINX_IMAGE}
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - wordpress
    networks:
      app_net:
        ipv4_address: 172.100.1.4

  wordpress:
    image: ${WORDPRESS_IMAGE}
    container_name: wordpress
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 9000:9000
    networks:
      app_net:
        ipv4_address: 172.100.1.2

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.100.1.0/24
