version: "3.8"

services:
  db:
    build: mariadb
    container_name: database
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql/
    networks:
      app_net:

  nginx:
    build: nginx
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - 80:80
    volumes:
      - wp-data:/app
    networks:
      app_net:

  wordpress:
    build: wordpress
    container_name: wordpress
    restart: always
    depends_on:
      - db
    ports:
      - 9000:9000
    volumes:
      - wp-data:/app
    networks:
      app_net:

networks:
  app_net:
    driver: bridge

volumes:
  wp-data:
  db-data:
