version: "3.8"

services:
  db:
    image: ${DB_IMAGE}
    container_name: database
    restart: always
    volumes:
      - db-data:/var/lib/mysql/
    networks:
      app_net:

  nginx:
    image: ${NGINX_IMAGE}
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - 80:80
    volumes:
      - wp-data:/app
    networks:
      app_net:

  wordpress:
    image: ${WORDPRESS_IMAGE}
    container_name: wordpress
    restart: always
    depends_on:
      - db
    volumes:
      - wp-data:/app
    networks:
      app_net:

  prometheus:
    image: ${PROMETHEUS_IMAGE}
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    networks:
      app_net:

networks:
  app_net:
    driver: bridge

volumes:
  wp-data:
  db-data:
