global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: "prometheus"

    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          alias: prometheus
