global:
  scrape_interval: 10s
  evaluation_interval: 10s

# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
          # - alertmanager:9093

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: "prometheus"

    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          alias: prometheus
