#!/bin/bash

MARIADB_DATABASE=${MARIADB_DATABASE:-""}
MARIADB_USER=${MARIADB_USER:-""}
MARIADB_PASSWORD=${MARIADB_PASSWORD:-""}

service mysql start

if [[ $MARIADB_DATABASE != "" ]]; then
    mysql -Bse "CREATE DATABASE IF NOT EXISTS \`$MARIADB_DATABASE\` CHARACTER SET utf8 COLLATE utf8_general_ci;"
    if [[ $MARIADB_USER != "" ]]; then
        mysql -Bse "GRANT ALL ON \`$MARIADB_DATABASE\`.* to '$MARIADB_USER'@'%' IDENTIFIED BY '$MARIADB_PASSWORD';"
    fi
fi
