name: docker build and push

on:
  workflow_dispatch:
    inputs:
      name:
        description: "name"
        required: true
        default: "workflow"
  push:
    branches: [main]

jobs:
  tests:
    name: "Build and test"
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4

      - name: login to docker registry
        uses: docker/login-action@v1.8.0
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build database image
        run: docker build -t database:latest mariadb

      - name: build nginx image
        run: docker build -t nginx:latest nginx

      - name: build wordpress image
        run: docker build -t wordpress:latest wordpress

      - name: tag and push database image
        run: |
          docker tag database ${{ secrets.DOCKER_REGISTRY }}/database
          docker push ${{ secrets.DOCKER_REGISTRY }}/database

      - name: tag and push nginx image
        run: |
          docker tag nginx ${{ secrets.DOCKER_REGISTRY }}/nginx
          docker push ${{ secrets.DOCKER_REGISTRY }}/nginx

      - name: tag and push wordpress image
        run: |
          docker tag wordpress ${{ secrets.DOCKER_REGISTRY }}/wordpress
          docker push ${{ secrets.DOCKER_REGISTRY }}/wordpress
