name: docker build and push

on:
  workflow_dispatch:
    inputs:
      name:
        description: "name"
        required: true
        default: "workflow"
  push:
    branches: [master]

jobs:
  tests:
    name: "Build and test"
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4

      - name: login to docker registry
        uses: docker/login-action@v1.8.0
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push database
        uses: docker/build-push-action@v2.4.0
        with:
          context: mariadb
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/database

      - name: build and push nginx
        uses: docker/build-push-action@v2.4.0
        with:
          context: nginx
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/nginx

      - name: build and push database wordpress
        uses: docker/build-push-action@v2.4.0
        with:
          context: wordpress
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/wordpress
